// <auto-generated />
using System;
using ChineseAuctionAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChineseAuctionAPI.Migrations
{
    [DbContext(typeof(SalesContextDB))]
    [Migration("20251221125336_MoreCreate")]
    partial class MoreCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChineseAuctionAPI.Models.Card", b =>
                {
                    b.Property<int>("CurdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CurdId"));

                    b.Property<int>("IdGift")
                        .HasColumnType("int");

                    b.Property<int?>("PackageIdPackage")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("CurdId");

                    b.HasIndex("PackageIdPackage");

                    b.HasIndex("userId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Donor", b =>
                {
                    b.Property<int>("IdDonor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDonor"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("L_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phonNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDonor");

                    b.ToTable("Donors");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Gift", b =>
                {
                    b.Property<int>("IdGift")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGift"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DonorIdDonor")
                        .HasColumnType("int");

                    b.Property<int>("IdDonor")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDrawn")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qeuntity")
                        .HasColumnType("int");

                    b.HasKey("IdGift");

                    b.HasIndex("DonorIdDonor");

                    b.ToTable("Gifts");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Gift_Order", b =>
                {
                    b.Property<int>("IdGiftOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGiftOrder"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("IdGift")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("giftsIdGift")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("IdGiftOrder");

                    b.HasIndex("OrderId");

                    b.HasIndex("giftsIdGift");

                    b.ToTable("Gifts_Orders");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("AmountOrders")
                        .HasColumnType("int");

                    b.Property<bool>("IsStatusDraft")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("userId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Package", b =>
                {
                    b.Property<int>("IdPackage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPackage"));

                    b.Property<int?>("Amount_Premium")
                        .HasColumnType("int");

                    b.Property<int>("Amount_Regular")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("IdPackage");

                    b.HasIndex("OrderId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhonNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.HasKey("userId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.winner", b =>
                {
                    b.Property<int>("IdWin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdWin"));

                    b.Property<int>("IdGift")
                        .HasColumnType("int");

                    b.Property<int>("giftsIdGift")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("IdWin");

                    b.HasIndex("giftsIdGift");

                    b.HasIndex("userId");

                    b.ToTable("Winners");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Card", b =>
                {
                    b.HasOne("ChineseAuctionAPI.Models.Package", null)
                        .WithMany("Cards")
                        .HasForeignKey("PackageIdPackage");

                    b.HasOne("ChineseAuctionAPI.Models.User", null)
                        .WithMany("cards")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Gift", b =>
                {
                    b.HasOne("ChineseAuctionAPI.Models.Donor", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorIdDonor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Gift_Order", b =>
                {
                    b.HasOne("ChineseAuctionAPI.Models.Order", "Orders")
                        .WithMany("GiftsInCart")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChineseAuctionAPI.Models.Gift", "gifts")
                        .WithMany("GiftOrders")
                        .HasForeignKey("giftsIdGift")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("gifts");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Order", b =>
                {
                    b.HasOne("ChineseAuctionAPI.Models.User", "Buyers")
                        .WithMany("Orders")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyers");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Package", b =>
                {
                    b.HasOne("ChineseAuctionAPI.Models.Order", null)
                        .WithMany("Packages")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.winner", b =>
                {
                    b.HasOne("ChineseAuctionAPI.Models.Gift", "gifts")
                        .WithMany()
                        .HasForeignKey("giftsIdGift")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChineseAuctionAPI.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("gifts");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Gift", b =>
                {
                    b.Navigation("GiftOrders");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Order", b =>
                {
                    b.Navigation("GiftsInCart");

                    b.Navigation("Packages");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Package", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("cards");
                });
#pragma warning restore 612, 618
        }
    }
}
