// <auto-generated />
using System;
using ChineseAuctionAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChineseAuctionAPI.Migrations
{
    [DbContext(typeof(SalesContextDB))]
    partial class SalesContextDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChineseAuctionAPI.Models.Buyers", b =>
                {
                    b.Property<int>("IdBayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBayer"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhonNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBayer");

                    b.ToTable("Buyers");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Donors", b =>
                {
                    b.Property<int>("IdDonor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDonor"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("L_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phonNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDonor");

                    b.ToTable("Donors");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Gifts_Orders", b =>
                {
                    b.Property<int>("IdGiftOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGiftOrder"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("IdGift")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("OrdersOrderId")
                        .HasColumnType("int");

                    b.Property<int>("giftsIdGift")
                        .HasColumnType("int");

                    b.HasKey("IdGiftOrder");

                    b.HasIndex("OrdersOrderId");

                    b.HasIndex("giftsIdGift");

                    b.ToTable("Gifts_Orders");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Orders", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("AmountOrders")
                        .HasColumnType("int");

                    b.Property<int>("BuyersIdBayer")
                        .HasColumnType("int");

                    b.Property<int>("IdBayer")
                        .HasColumnType("int");

                    b.Property<int>("IdPackage")
                        .HasColumnType("int");

                    b.Property<int>("PackagesIdPackage")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderId");

                    b.HasIndex("BuyersIdBayer");

                    b.HasIndex("PackagesIdPackage");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Packages", b =>
                {
                    b.Property<int>("IdPackage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPackage"));

                    b.Property<int?>("Amount_PrimPremium")
                        .HasColumnType("int");

                    b.Property<int>("Amount_Regular")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("IdPackage");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.gifts", b =>
                {
                    b.Property<int>("IdGift")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGift"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DonorsIdDonor")
                        .HasColumnType("int");

                    b.Property<int>("IdDonor")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qeuntity")
                        .HasColumnType("int");

                    b.HasKey("IdGift");

                    b.HasIndex("DonorsIdDonor");

                    b.ToTable("gifts");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Gifts_Orders", b =>
                {
                    b.HasOne("ChineseAuctionAPI.Models.Orders", "Orders")
                        .WithMany()
                        .HasForeignKey("OrdersOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChineseAuctionAPI.Models.gifts", "gifts")
                        .WithMany()
                        .HasForeignKey("giftsIdGift")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("gifts");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Orders", b =>
                {
                    b.HasOne("ChineseAuctionAPI.Models.Buyers", "Buyers")
                        .WithMany()
                        .HasForeignKey("BuyersIdBayer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChineseAuctionAPI.Models.Packages", "Packages")
                        .WithMany()
                        .HasForeignKey("PackagesIdPackage")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyers");

                    b.Navigation("Packages");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.gifts", b =>
                {
                    b.HasOne("ChineseAuctionAPI.Models.Donors", "Donors")
                        .WithMany()
                        .HasForeignKey("DonorsIdDonor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donors");
                });
#pragma warning restore 612, 618
        }
    }
}
